/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 angular.glb -T 
Files: angular.glb [397KB] > /Users/kimcy/Development/KDX/3D-Portfolio/public/models/angular-transformed.glb [21.72KB] (95%)
Author: Ramadhan Mohammed Mkoma (https://sketchfab.com/ramadhanmkoma9)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/angular-brand-480c6c17299f4b6c9a557f2728ad3906
Title: Angular Brand
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/angular-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="logo" position={[0, 0, 151.109]} rotation={[-Math.PI / 2, 0, 2.904]} scale={190.107}>
            <mesh name="logo_Material001_0" geometry={nodes.logo_Material001_0.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/angular-transformed.glb')
