/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook.glb -T 
Files: macbook.glb [2.55MB] > /Users/kimcy/Development/KDX/3D-Portfolio/public/models/macbook-transformed.glb [166.82KB] (93%)
Author: KangaroOz 3D (https://sketchfab.com/KangaroOz-3D)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-2021-37763335f74b497e91906986b170b5d1
Title: MacBook Pro 2021
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MacBook(props) {
  const { nodes, materials } = useGLTF('/models/macbook-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.MacBookPro} />
    </group>
  )
}

useGLTF.preload('/models/macbook-transformed.glb')
